require "aaron.options"
require "aaron.keymaps"
require "aaron.plugins"
require "aaron.colorscheme"
require "aaron.lsp"
-- require "user.telescope"
-- require "user.nvim-tree"
-- require "user.treesitter"
-- require "user.neogit"
-- require "user.bufferline"
-- require "user.impatient"
-- require "user.autocommands"
